version: "3"
services:
  home_led_server:
    build:
      context: ./api
      dockerfile: Dockerfile-dev
    ports:
      - "3080:3080"
    container_name: home_led_server
    volumes:
      - ./api:/usr/src/app/api
      - /usr/src/app/api/node_modules
    privileged: true
