version: "3"
services:
  home_led_ui:
    build:
      context: ./app
      dockerfile: Dockerfile-dev
    ports:
      - "8384:8080"
    container_name: home_led_ui
    volumes:
      - ./app:/usr/src/app/home_led_app
      - /usr/src/app/home_led_app/node_modules
