FROM node:10

RUN apt-get update && apt-get install python -y
RUN apt-get install python3-pip -y
RUN pip install rpi-ws281x

WORKDIR /usr/src/app/api

COPY package*.json ./

RUN npm install


EXPOSE 3080

CMD ["npm", "run", "dev"]
